spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null
  application:
    name: self-logic-lab-boot






logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%X{selfTraceId}]){cyan} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
  level:
    root: info