spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null
  application:
    name: self-logic-lab-boot
#  data: 本地暂无redis实例
#    redis:
#      host: localhost
#      port: 6379
#      password:

# http://localhost:8080/actuator/metrics/executor.active
management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "metrics,threaddump"


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    disable-swagger-default-url: true



logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%X{selfTraceId}]){cyan} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
  level:
    root: info


